# Generated by Django 4.2.1 on 2023-06-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('band_name', models.CharField(max_length=100)),
                ('band_price', models.IntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='bandimg')),
                ('band_number', models.CharField(max_length=100)),
                ('band_address', models.CharField(max_length=100)),
                ('band_location', models.CharField(max_length=100)),
                ('band_email', models.CharField(max_length=100)),
                ('room_count', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('genre_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandBooking',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_location', models.TextField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_bookings', to='band.band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(to='band.genre'),
        ),
    ]
